Repository mdflynn/Crate, pull requests merged in 2021-02, with the labels that each got.

#59 Create API Contract for User Mutation
  code/api/.gitignore
  code/api/package-lock.json
  code/api/package.json
  code/api/src/config/database.json
  code/api/src/migrations/modify_user_add_new_fields.js
  code/api/src/modules/mocks/index.js
  code/api/src/modules/product/model.js
  code/api/src/modules/subscription/model.js
  code/api/src/modules/user/model.js
  code/api/src/modules/user/mutations.js
  code/api/src/modules/user/resolvers.js
  code/api/src/modules/user/tests/userMutation.test.js
  code/api/src/modules/user/tests/userResolver.test.js
  code/api/src/modules/user/types.js
  code/api/src/seeders/1-user.js
  code/api/src/setup/schema/queries.js
Labels: back-end 🔙, enhancement 🌟

#61 Feature/profile display
  code/web/src/modules/user/Profile.js
Labels: enhancement 🌟, front-end 🍱

#65 Feature/order history
  code/web/src/modules/user/OrderHistory.js
  code/web/src/modules/user/Profile.js
Labels: enhancement 🌟, front-end 🍱

#66 Feature/modal
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/api/actions.js
  code/web/src/ui/form/EditProfileForm.js
  code/web/src/ui/input/Input.js
  code/web/src/ui/modal/ProfileModal.js
  code/web/src/ui/modal/index.js
Labels: deliverable 🎁, enhancement 🌟, front-end 🍱, styling/UI 🎨

#71 Feature/profile display testing
  code/api/package-lock.json
  code/api/package.json
  code/web/package-lock.json
  code/web/package.json
  code/web/src/modules/user/OrderHistory.js
  code/web/src/modules/user/Profile.js
  code/web/src/tests/OrderHistory.test.js
Labels: enhancement 🌟

#74 Connect fe be
  code/api/src/modules/user/mutations.js
  code/api/src/modules/user/resolvers.js
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/api/actions.js
  code/web/src/modules/user/api/state.js
  code/web/src/ui/form/EditProfileForm.js
  code/web/src/ui/modal/ProfileModal.js
Labels: deliverable 🎁, front-end 🍱

#76 Update 1st UX (FE & BE)
  code/api/src/modules/user/mutations.js
  code/api/src/modules/user/resolvers.js
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/Signup.js
  code/web/src/modules/user/api/actions.js
  code/web/src/modules/user/profile-placeholder.svg
  code/web/src/ui/form/EditProfileForm.js
  code/web/src/ui/modal/ProfileModal.js
Labels: enhancement 🌟

#77 Profile styling
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/mockOrderData.js
  code/web/src/ui/form/EditProfileForm.js
  code/web/src/ui/modal/ProfileModal.js
Labels: bug 🐞, front-end 🍱
